name: seller_loop
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.8+9

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  image_picker: ^1.1.2
  flutter_screenutil: ^5.9.0
  permission_handler: ^11.3.0
  path_provider: ^2.0.15
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  flutter_dotenv: ^6.0.0
  dotted_border: ^2.1.0
  dio: ^5.4.3+1
  webview_flutter: ^4.8.0
  url_launcher: ^6.2.6
  package_info_plus: ^8.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true

  # One source image for both platforms
  image_path: "assets/deazly_icon.png"

  # Android adaptive icon (optional but recommended)
  adaptive_icon_foreground: "assets/deazly_icon.png"
  # adaptive_icon_monochrome: "assets/png/deazly_icon_monochrome.png"  # optional for Android 13+

  # iOS
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
    - assets/profile/

# --- Native Splash Configuration ---
# Make sure these image files exist. Suggested sizes below.
flutter_native_splash:
  android: true
  ios: true
  web: false

  # Light mode
  color: "#FFFFFF"
  image: assets/deazly_logo.png





  # Android 12+ requires separate section
  android_12:
    image: assets/deazly_logo.png


    color: "#FFFFFF"

    icon_background_color: "#FFFFFF"


  # iOS layout controls (keep centered logo)
  ios_content_mode: center
  fullscreen: true
